<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CinemaBooking.Catalog.Core\CinemaBooking.Catalog.Core.csproj" />
    <ProjectReference Include="..\CinemaBooking.Catalog.Infrastructure\CinemaBooking.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\CinemaBooking.Security\CinemaBooking.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
